# https://gitlab.com/nanuchi/youtube-tutorial-series/-/blob/master/demo-kubernetes-components/mongo-express.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express # https://hub.docker.com/_/mongo-express
          ports:
            - containerPort: 8081
          # Environment Variable you can find on docker hob mongo-express documentation
          # we need 2 thing:
          # Which database to connect?
          #  -> ME_CONFIG_MONGODB_SERVER
          # Which credentials to authenticated?
          # -> ME_CONFIG_MONGODB_ADMINUSERNAME
          # -> ME_CONFIG_MONGODB_ADMINPASSWORD
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret # we will read username and pass from the same secret that we created
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              # we can write directly 'value' here but we will going to get the value from 'configMap' which is the external configuration so that will centralized and also other component can use it
              # './09_ConfigMap.png'
              # so we will define configMap in './mongo-configmap.yaml'
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # to make this service as external service we have to make it as "LoadBalancer"
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # so this is the port where external ip address will be open
